# -*- coding: utf-8 -*-
"""delivery.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zxNhP39CKE3YeTwdzkhmpBNs8zTJeqIx
"""

import heapq

orders = []

heapq.heappush(orders, (30, "Pizza"))
heapq.heappush(orders, (15, "Burger"))
heapq.heappush(orders, (20, "Biryani"))
heapq.heappush(orders, (10, "Sandwich"))

print("Delivery Order:")

while orders:
    time, food = heapq.heappop(orders)
    print(food, "-", time, "minutes")